import Head from 'next/head'
import Layout from '@/components/layouts/Layout/Layout'
import { ReactElement } from 'react'
import BodyLayout from '@/components/layouts/BodyLayout/BodyLayout'
import Row from '@/components/layouts/layoutCompoents/Row/Row'
import Breadcramps from '@/components/sections/Breadcramps/Breadcramps'
import Section from '@/components/layouts/layoutCompoents/Section/Section'
import Ad from '@/components/ads/Ad/Ad'
import Placeholder from '@/components/Placeholder/Placeholder'
import Divider from '@/components/layouts/layoutCompoents/Divider/Divider'
import Teaser from '@/components/teasers/Teaser/Teaser'

import Image from 'next/image'
import copy from '@/public/assets/icons/copy.svg'
import arrow from '@/public/assets/icons/arrow.svg'
import mail from '@/public/assets/icons/mail.svg'
import print from '@/public/assets/icons/print.svg'
import IconButton from '@/components/IconButton/IconButton'

const Index = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Section>
          <Breadcramps />
        </Section>
        <Section>
          <p style={{ marginTop: 10, marginBottom: 10 }}>
            Musiker in Beffendorf
          </p>
          <h1 style={{ marginBottom: 10 }}>
            Akkordeonorchester präsentiert eigene CD
          </h1>
          <p style={{ marginBottom: 30 }}>Ute Lauble 22.02.2023 - 15:48 Uhr</p>
        </Section>
        <Section>
          <Row spacing={10}>
            <Row.Item columns={{ lg: 3 / 2, sm: 1 }}>
              <>
                <Placeholder style={{ minHeight: 343 }} />
                <p style={{ marginTop: 10, marginBottom: 30 }}>
                  Die Musiker sind stolz ihre erste eigene CD. Foto: Lauble
                </p>
                <div style={{ display: 'flex' }}>
                  <IconButton>
                    <Image src={print} alt="search" />
                  </IconButton>
                  <IconButton>
                    <Image src={arrow} alt="search" />
                  </IconButton>
                  <IconButton>
                    <Image src={copy} alt="search" />
                  </IconButton>
                  <IconButton>
                    <Image src={mail} alt="search" />
                  </IconButton>
                </div>
                <h4 style={{ marginTop: 10, marginBottom: 30 }}>
                  Lange musste man warten, doch jetzt endlich ist sie da. Das
                  Akkordeonorchester Beffendorf präsentiert seine neue CD.
                </h4>
                <p style={{ marginTop: 10, marginBottom: 30 }}>
                  Mit dem Stück „Games of Throne“, eröffnete das
                  Akkordeonorchester Beffendorf musikalisch den Abend im
                  Gemeindehaus, an dem sie voller Freude ihre neue CD vorstellen
                  konnten.
                </p>
                <p style={{ marginTop: 10, marginBottom: 30 }}>
                  Eigentlich, so der Vorsitzende Eugen Werner, hätte sie schon
                  im Jahr 2022 fertig werden sollen, aber verschiedene Gründe
                  hätten die Auslieferung verzögert. Doch „nach langem Warten
                  ist sie endlich da.“
                </p>

                <Divider style={{ marginBottom: 20 }} />
                <Section title="Lesen Sie auch" fullWidth>
                  <Row spacing={10} columns={{ lg: 3, sm: 1, xs: 1 }}>
                    {[0, 1, 2].map((value) => {
                      return (
                        <Row.Item key={value}>
                          <Teaser
                            paidContent={false}
                            enm="standard"
                            text="Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet."
                            title="Teaser,  enum: standard"
                          />
                        </Row.Item>
                      )
                    })}
                  </Row>
                </Section>
                <Divider style={{ marginBottom: 20 }} />
                <h3 style={{ marginTop: 20, marginBottom: 20 }}>
                  Vereinsleben durcheinander gewirbelt
                </h3>
                <p style={{ marginTop: 10, marginBottom: 30 }}>
                  Corona, so Eugen Werner, hat so manches Vereinsleben
                  durcheinander gewirbelt. Das Akkordeonorchester Beffendorf
                  nutzte diese Zeit und bewarb sich beim Förderprogramm
                  „Neustart Amateurmusik“ des Bundesmusikverbands Chor &
                  Orchester und bekam den Zuschlag. „Wir halten zusammen –
                  gemeinsam mit Musik durch die Coronazeit“, lautete der
                  Projekttitel. Die Argumentation „Mit viel Engagement und
                  Einsatz haben wir versucht, auf dem Weg zu bleiben. Das
                  Ergebnis aus den Proben nach Playalongs, in kleinen Gruppen,
                  Stimmproben sowie dem Üben zu Hause und dem Neustart nach
                  langen Monaten getrennt seins möchten wir auf einer CD
                  festhalten“, überzeugte die Jury.
                </p>
                <h3 style={{ marginTop: 20, marginBottom: 20 }}>
                  Vereinsleben durcheinander gewirbelt
                </h3>
                <p style={{ marginTop: 10, marginBottom: 30 }}>
                  Corona, so Eugen Werner, hat so manches Vereinsleben
                  durcheinander gewirbelt. Das Akkordeonorchester Beffendorf
                  nutzte diese Zeit und bewarb sich beim Förderprogramm
                  „Neustart Amateurmusik“ des Bundesmusikverbands Chor &
                  Orchester und bekam den Zuschlag. „Wir halten zusammen –
                  gemeinsam mit Musik durch die Coronazeit“, lautete der
                  Projekttitel. Die Argumentation „Mit viel Engagement und
                  Einsatz haben wir versucht, auf dem Weg zu bleiben. Das
                  Ergebnis aus den Proben nach Playalongs, in kleinen Gruppen,
                  Stimmproben sowie dem Üben zu Hause und dem Neustart nach
                  langen Monaten getrennt seins möchten wir auf einer CD
                  festhalten“, überzeugte die Jury.
                </p>
                <Ad />
              </>
            </Row.Item>
            <Row.Item columns={{ lg: 3 / 1, sm: 1 }}>
              <>
                <Ad title="Anzeige" />
                <Ad />
                <Ad />
              </>
            </Row.Item>
          </Row>
        </Section>
        <Section title="Lesen Sie auch">
          <Row spacing={10} columns={{ lg: 4, sm: 2, xs: 1 }}>
            {[0, 1, 2, 3].map((value) => {
              return (
                <Row.Item key={value}>
                  <Teaser
                    paidContent={false}
                    enm="standard"
                    text="Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet."
                    title="Teaser,  enum: standard"
                  />
                </Row.Item>
              )
            })}
          </Row>
        </Section>
      </>
    </>
  )
}

Index.getLayout = (page: ReactElement) => {
  return (
    <Layout>
      <BodyLayout>{page}</BodyLayout>
    </Layout>
  )
}

export default Index
