import Head from 'next/head'
import Layout from '@/components/layouts/Layout/Layout'
import { ReactElement } from 'react'
import BodyLayout from '@/components/layouts/BodyLayout/BodyLayout'

const Index = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <div>lets get started</div>
      </>
    </>
  )
}

Index.getLayout = (page: ReactElement) => {
  return (
    <Layout>
      <BodyLayout>{page}</BodyLayout>
    </Layout>
  )
}

export default Index
