import Head from 'next/head'
import Wall from '@/components/bticks/Wall/Wall'
import { components } from 'schema'

export async function getServerSideProps() {
  const res = await fetch(`http://msh-news.intetics.com:8080/stz/homepage`)
  const data: components['schemas']['Wall'] = await res.json()
  console.log('index', data)

  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: { data }, // will be passed to the page component as props
  }
}

interface IndexProps {
  data: components['schemas']['Wall']
}
const Index = ({ data }: IndexProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Wall data={data} />
      </>
    </>
  )
}

// Index.getLayout = (page: ReactElement) => {
//   return (
//     <Layout>
//       <BodyLayout>{page}</BodyLayout>
//     </Layout>
//   )
// }

export default Index
