import Head from 'next/head'
import Layout from '@/components/layouts/Layout/Layout'
import { ReactElement } from 'react'
import BodyLayout from '@/components/layouts/BodyLayout/BodyLayout'
import Teaser from '@/components/teasers/Teaser/Teaser'
import Row from '@/components/layouts/layoutCompoents/Row/Row'
import Breadcramps from '@/components/sections/Breadcramps/Breadcramps'
import Section from '@/components/layouts/layoutCompoents/Section/Section'
import Ad from '@/components/ads/Ad/Ad'
import Divider from '@/components/layouts/layoutCompoents/Divider/Divider'
import MehrButton from '@/components/MehrButton/MehrButton'

const Index = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Section>
          <Breadcramps />
        </Section>
        <Section>
          <Divider />
        </Section>
        <Section>
          <Row spacing={10} columns={{ lg: 2, sm: 1 }}>
            {[0, 1].map((value) => {
              return (
                <Row.Item key={value}>
                  <Teaser
                    paidContent={false}
                    enm="compact"
                    text="The largest community of photo enthusiasts"
                    title="Teaser,  enum: top, imageCount > 1"
                  />
                </Row.Item>
              )
            })}
          </Row>
        </Section>

        <Section>
          <Row spacing={10}>
            <Row.Item columns={{ lg: 3 / 2, xs: 1 }}>
              <Row spacing={10} columns={{ lg: 2, xs: 1 }}>
                {[0, 1, 2, 3, 4, 5].map((value) => {
                  return (
                    <Row.Item key={value}>
                      <Teaser
                        paidContent={false}
                        enm="standard"
                        text="Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet."
                        title="Teaser,  enum: standard"
                      />
                    </Row.Item>
                  )
                })}
              </Row>
            </Row.Item>
            <Row.Item columns={{ lg: 3 / 1, xs: 1 }}>
              <>
                <Ad />
                <Ad />
                <Ad />
              </>
            </Row.Item>
          </Row>
        </Section>

        <Section>
          <Row spacing={10} columns={{ lg: 2, sm: 1 }}>
            {[0, 1].map((value) => {
              return (
                <Row.Item key={value}>
                  <Teaser
                    paidContent={false}
                    enm="compact"
                    text="The largest community of photo enthusiasts"
                    title="Teaser,  enum: top, imageCount > 1"
                  />
                </Row.Item>
              )
            })}
          </Row>
        </Section>

        <Section>
          <Row spacing={10}>
            <Row.Item columns={{ lg: 3 / 2, xs: 1 }}>
              <Row spacing={10} columns={{ lg: 2, xs: 1 }}>
                {[0, 1, 2, 3, 4, 5].map((value) => {
                  return (
                    <Row.Item key={value}>
                      <Teaser
                        paidContent={false}
                        enm="standard"
                        text="Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet."
                        title="Teaser,  enum: standard"
                      />
                    </Row.Item>
                  )
                })}
              </Row>
            </Row.Item>
            <Row.Item columns={{ lg: 3 / 1, xs: 1 }}>
              <>
                <Ad />
                <Ad />
              </>
            </Row.Item>
          </Row>
        </Section>

        <Section>
          <Row spacing={10} columns={{ lg: 3, md: 2, xs: 1 }}>
            {[0, 1, 2, 3, 4, 5].map((value) => {
              return (
                <Row.Item key={value}>
                  <Teaser
                    paidContent={false}
                    enm="standard"
                    text="Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet."
                    title="Teaser,  enum: standard"
                  />
                </Row.Item>
              )
            })}
          </Row>
        </Section>
        <Section>
          <MehrButton>Mehr Nachrichten</MehrButton>
        </Section>
      </>
    </>
  )
}

Index.getLayout = (page: ReactElement) => {
  return (
    <Layout>
      <BodyLayout>{page}</BodyLayout>
    </Layout>
  )
}

export default Index
