import Head from 'next/head'
import Layout from '@/components/layouts/Layout/Layout'
import { ReactElement } from 'react'
import BodyLayout from '@/components/layouts/BodyLayout/BodyLayout'
import Teaser from '@/components/bticks/Teaser/Teaser'
import Row from '@/components/layouts/layoutComponents/Row/Row'

import Section from '@/components/layouts/layoutComponents/Section/Section'
import Ad from '@/components/bticks/ads/Ad/Ad'
import Divider from '@/components/layouts/layoutComponents/Divider/Divider'
import MehrButton from '@/components/MehrButton/MehrButton'
import Breadcramps from '@/components/sections/Breadcramps/Breadcramps'
import Link from 'next/link'
import Image from 'next/image'
import home from '@/public/assets/icons/home.svg'
import { components } from 'schema'
import { GetServerSideProps } from 'next/types'

export const getServerSideProps: GetServerSideProps = async (context) => {
  //@ts-ignore
  const { ressortId } = context.params
  const res = await fetch(
    `http://msh-news.intetics.com:8080/stz/article/a26d8a68-b297-11ed-afa1-0242ac120002`
  )
  const data: components['schemas']['Wall'] = await res.json()
  console.log('ressort', data)
  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: { data }, // will be passed to the page component as props
  }
}

const Ressort = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Section>
          <Breadcramps>
            <Link href="/">
              <Image width={20} height={20} src={home} alt="home" />
            </Link>
            <Link href="/article">BW von oben</Link>
            <Link href="/ressort">Blaulicht</Link>
          </Breadcramps>
        </Section>
        <Section>
          <Divider />
        </Section>
        <Section>
          <Row spacing={10} columns={{ lg: 2, sm: 1 }}>
            {[0, 1].map((value) => {
              return (
                <Row.Item key={value}>
                  <Teaser
                    paidContent={false}
                    enm="compact"
                    text="The largest community of photo enthusiasts"
                    title="Teaser,  enum: top, imageCount > 1"
                  />
                </Row.Item>
              )
            })}
          </Row>
        </Section>

        <Section>
          <Row spacing={10}>
            <Row.Item columns={{ lg: 3 / 2, xs: 1 }}>
              <Row spacing={10} columns={{ lg: 2, xs: 1 }}>
                {[0, 1, 2, 3, 4, 5].map((value) => {
                  return (
                    <Row.Item key={value}>
                      <Teaser
                        paidContent={false}
                        enm="standard"
                        text="Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet."
                        title="Teaser,  enum: standard"
                      />
                    </Row.Item>
                  )
                })}
              </Row>
            </Row.Item>
            <Row.Item columns={{ lg: 3 / 1, xs: 1 }}>
              <>
                <Ad />
                <Ad />
                <Ad />
              </>
            </Row.Item>
          </Row>
        </Section>

        <Section>
          <Row spacing={10} columns={{ lg: 2, sm: 1 }}>
            {[0, 1].map((value) => {
              return (
                <Row.Item key={value}>
                  <Teaser
                    paidContent={false}
                    enm="compact"
                    text="The largest community of photo enthusiasts"
                    title="Teaser,  enum: top, imageCount > 1"
                  />
                </Row.Item>
              )
            })}
          </Row>
        </Section>

        <Section>
          <Row spacing={10}>
            <Row.Item columns={{ lg: 3 / 2, xs: 1 }}>
              <Row spacing={10} columns={{ lg: 2, xs: 1 }}>
                {[0, 1, 2, 3, 4, 5].map((value) => {
                  return (
                    <Row.Item key={value}>
                      <Teaser
                        paidContent={false}
                        enm="standard"
                        text="Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet."
                        title="Teaser,  enum: standard"
                      />
                    </Row.Item>
                  )
                })}
              </Row>
            </Row.Item>
            <Row.Item columns={{ lg: 3 / 1, xs: 1 }}>
              <>
                <Ad />
                <Ad />
              </>
            </Row.Item>
          </Row>
        </Section>

        <Section>
          <Row spacing={10} columns={{ lg: 3, md: 2, xs: 1 }}>
            {[0, 1, 2, 3, 4, 5].map((value) => {
              return (
                <Row.Item key={value}>
                  <Teaser
                    paidContent={false}
                    enm="standard"
                    text="Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet."
                    title="Teaser,  enum: standard"
                  />
                </Row.Item>
              )
            })}
          </Row>
        </Section>
        <Section>
          <MehrButton>Mehr Nachrichten</MehrButton>
        </Section>
      </>
    </>
  )
}

// Index.getLayout = (page: ReactElement) => {
//   return (
//     <Layout>
//       <BodyLayout>{page}</BodyLayout>
//     </Layout>
//   )
// }

export default Ressort

{
  /* <StyledLayout>
<StyledWrapper>
  {header?.[0] && (
    <Header data={header[0] as components['schemas']['Header']} />
  )}
  <StyledBody>
    <StyledBodyLayout>
      <StyledMainContent>
        <AdBillboard />
        <StyledContent>
          {pagecontent?.[0] && (
            <PageContent
              data={
                pagecontent[0] as components['schemas']['PageContent']
              }
            />
          )}
        </StyledContent>
        <StyledFooter>
          {' '}
          {footer?.[0] && (
            <Footer
              data={footer[0] as components['schemas']['Footer']}
            />
          )}
        </StyledFooter>
      </StyledMainContent>
      <StyledAdSkyscraper />
    </StyledBodyLayout>
  </StyledBody>
</StyledWrapper>
</StyledLayout>
</> */
}
